@startjson json

title JSON Schema

{
  "description": "Опис предметної області ПП",
  "type": "object",
  "properties": {
    "consumer": {
      "description": "Опис споживача",
      "type": "object",
      "properties": {
        "name": {
          "description": "Ім'я споживача",
          "type": "string"
        },
        "photo": {
          "description": "Фото споживача",
          "type": "BinData"
        },
        "info": {
          "description": "Анкета користувача",
          "type": "object",
          "properties": {
            "name": {
              "description": "Ім'я користувача",
              "type": "string"
            },
            "photo": {
              "description": "Фото користувача",
              "type": "BinData"
            },
            "desc": {
              "description": "Короткий опис користувача",
              "type": "string"
            },
            "contacts": {
              "description": "Контактні дані користувача",
              "type": "string"
            },
            "full_info": {
              "description": "Докладна інформація про користувача",
              "type": "object",
              "properties": {
                "name": {
                  "description": "Ім'я користувача",
                  "type": "string"
                },
                "photos": {
                  "description": "Фото користувача",
                  "type": "array",
                  "items": {
                    "description": "Фото користувача",
                    "type": "BinData"
                  }
                },
                "desc": {
                  "description": "Повний опис користувача",
                  "type": "string"
                },
                "contacts": {
                  "description": "Контактні дані користувача",
                  "type": "string"
                },
                "age": {
                  "description": "Вік користувача",
                  "type": "number"
                },
                "height": {
                  "description": "Зріст користувача",
                  "type": "number"
                }
              },
              "required": [
                "name",
                "photo",
                "desc",
                "age"
              ]
            }
          },
          "required": [
            "name",
            "photo",
            "desc"
          ]
        }
      },
      "required": [
        "name",
        "photo"
      ]
    }
  }
}

@endjson