name: Program Code Linter
on: push
jobs:
  ProgramCodeLinter:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Lint Program Code
        uses: github/super-linter@v4
        env:
          VALIDATE_JAVASCRIPT_STANDART: true
          FILTER_REGEX_INCLUDE: ./*.js$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
